# Generated by Django 5.1.3 on 2024-11-29 03:44

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmblemasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30, null=True)),
                ('moedas', models.IntegerField(default=0)),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('icone', models.ImageField(upload_to='imagens/')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitanteemblemas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmblemaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('emblema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System.emblemasmodel')),
            ],
        ),
        migrations.CreateModel(
            name='JA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(max_length=150, null=True, verbose_name='Motivo')),
                ('data', models.DateField(default=datetime.date.today, null=True)),
                ('data2', models.DateField(default=datetime.date.today, null=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogJA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto Aval')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('aval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='System.ja', verbose_name='aval')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarioautor', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='System.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostagemJornal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=90, null=True)),
                ('descricao', models.TextField(max_length=170, null=True)),
                ('texto', django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Postagem')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantepostagem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto postagem')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='System.postagemjornal', verbose_name='postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Treinamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30, null=True)),
                ('treinamento', django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Treinamentos')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitantetreinamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprovado', models.TextField(blank=True, max_length=70, null=True)),
                ('reprovado', models.TextField(blank=True, max_length=70, null=True)),
                ('obs', models.TextField(max_length=150, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitanterelatorio', to=settings.AUTH_USER_MODEL)),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.treinamentos')),
            ],
        ),
        migrations.CreateModel(
            name='LogTreinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto relatorio')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='System.treinamentos', verbose_name='treinamento')),
            ],
        ),
    ]
