# Generated by Django 5.1.3 on 2024-11-30 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_logdocumentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policial', models.TextField(max_length=150, null=True, verbose_name='Policial')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('policial', models.TextField(blank=True, max_length=70, null=True, verbose_name='Policial')),
                ('obs', models.TextField(max_length=150, null=True, verbose_name='Observações')),
                ('requerimento', models.CharField(choices=[('Promoção', 'Promoção'), ('Rebaixamento', 'Rebaixamento'), ('Advertência', 'Advertência'), ('Banimento', 'Banimento')], max_length=50, null=True, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Em análise...', 'Em análise...'), ('Reprovado', 'Reprovado')], default='Em análise...', max_length=50, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitanterequerimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
