# Generated by Django 5.1.3 on 2024-11-30 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_logtimeline_requerimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto requerimento')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
                ('requerimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='System.requerimento', verbose_name='requerimento')),
            ],
        ),
    ]
