# Generated by Django 5.1.3 on 2024-12-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_logrequerimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtimeline',
            name='requerimento',
            field=models.CharField(choices=[('Promoção', 'Promoção'), ('Rebaixamento', 'Rebaixamento'), ('Advertência', 'Advertência'), ('Banimento', 'Banimento')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
