# Generated by Django 5.1.3 on 2024-12-01 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_alter_logtimeline_requerimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=150, null=True, verbose_name='Texto relatorio')),
                ('datatime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
