# Generated by Django 5.1.3 on 2024-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_requerimento_cargo_alter_logtimeline_requerimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque1', models.TextField(max_length=150, null=True, verbose_name='Destaque')),
                ('destaque2', models.TextField(max_length=150, null=True, verbose_name='Destaque')),
            ],
        ),
    ]
