# Generated by Django 5.1.3 on 2024-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0014_dporelatório_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='obs',
            field=models.TextField(max_length=400, null=True, verbose_name='Observações'),
        ),
    ]
