# Generated by Django 5.1.3 on 2024-11-23 01:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='150 characters or fewer. Letters (uppercase and lowercase), digits, @, :, -, and _ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters (uppercase and lowercase), numbers, @, :, -, and _ characters.', regex='^[a-zA-Z0-9@_:.,\\-!=]+$')], verbose_name='usuário')),
                ('patente', models.CharField(choices=[('', 'Selecione a Patente'), ('Agente', 'Agente'), ('Cabo', 'Cabo'), ('Sargento', 'Sargento'), ('Tenente', 'Tenente'), ('Capitão', 'Capitão'), ('Major', 'Major'), ('Coronel', 'Coronel'), ('General', 'General'), ('Comandante', 'Comandante'), ('Sócio', 'Sócio'), ('Inspetor', 'Inspetor'), ('Inspetor-Chefe', 'Inspetor-Chefe'), ('Coordenador', 'Coordenador'), ('Supervisor', 'Supervisor'), ('Administrador', 'Administrador'), ('Procurador', 'Procurador'), ('Ministro', 'Ministro'), ('Escrivão', 'Escrivão'), ('Diretor', 'Diretor'), ('Diretor-Fundador', 'Diretor-Fundador'), ('Embaixador', 'Embaixador'), ('Vice-Presidente', 'Vice-Presidente'), ('Presidente', 'Presidente'), ('Acionista', 'Acionista'), ('Conselheiro', 'Conselheiro'), ('Suplente', 'Suplente'), ('Co-Fundador', 'Co-Fundador'), ('Sub-Fundador', 'Sub-Fundador'), ('Fundador', 'Fundador'), ('Supremo', 'Supremo')], default='Soldado', max_length=50)),
                ('moedas', models.IntegerField(default=0)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('patente_order', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
