# Generated by Django 5.1.3 on 2024-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeAcesso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policialusuario',
            name='patente',
            field=models.CharField(choices=[('', 'Selecione a Patente'), ('Agente', 'Agente'), ('Cabo', 'Cabo'), ('Sargento', 'Sargento'), ('Tenente', 'Tenente'), ('Capitão', 'Capitão'), ('Major', 'Major'), ('Coronel', 'Coronel'), ('General', 'General'), ('Comandante', 'Comandante'), ('Sócio', 'Sócio'), ('Inspetor', 'Inspetor'), ('Inspetor-Chefe', 'Inspetor-Chefe'), ('Coordenador', 'Coordenador'), ('Supervisor', 'Supervisor'), ('Administrador', 'Administrador'), ('Procurador', 'Procurador'), ('Ministro', 'Ministro'), ('Escrivão', 'Escrivão'), ('Diretor', 'Diretor'), ('Diretor-Fundador', 'Diretor-Fundador'), ('Embaixador', 'Embaixador'), ('Vice-Presidente', 'Vice-Presidente'), ('Presidente', 'Presidente'), ('Acionista', 'Acionista'), ('Conselheiro', 'Conselheiro'), ('Suplente', 'Suplente'), ('Co-Fundador', 'Co-Fundador'), ('Sub-Fundador', 'Sub-Fundador'), ('Fundador', 'Fundador'), ('Supremo', 'Supremo')], default='Agente', max_length=50),
        ),
    ]
