# Generated by Django 5.1.3 on 2024-12-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControleDeAcesso', '0002_alter_policialusuario_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='policialusuario',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Demitido', 'Demitido'), ('Banido', 'Banido')], default='Ativo', max_length=50),
        ),
    ]
